blank_issues_enabled: false
contact_links:
  - name: NeoSpace support
    url: https://help.neospace.com/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the NeoSpace Python library.
      If you're having general trouble with the NeoSpace API, please visit our help center to get support.
