# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:  
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
      env:
        RYE_VERSION: '0.35.0'
        RYE_INSTALL_OPTION: '--yes'

    - name: Install dependencies
      run: rye sync --all-features

    - name: Build Wheel Package
      run: |
          set -eux
          mkdir -p dist
          rye build --clean

    - name: Generate Random Tag
      id: random_tag
      run: echo "tag=v1.0.0-$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "dist/*"
        artifactContentType: "application/zip"
        name: "Release main ${{ steps.random_tag.outputs.tag }}"
        prerelease: "true"
        tag: ${{ steps.random_tag.outputs.tag }}
              
